# -*- coding: utf-8 -*-
"""2025-07-07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtJAnK9NbRGO3sEVDNdwlGibzahN5LSx
"""

import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[-2,4],[1,3]])
C = np.array([[2,-5],[3,-2]])
D = np.array([[5,-1,3],[-4,3,-6],[-3,1,2]])

# A[2,2]+B[1,1]
print(A[1,1]+B[0,0])

# 행렬 A의 전치행렬
print((A.T))

print((A.T).T)

# A_T + B_T
print(A.T+B.T)

# (A+B)_T
print((A+B).T)

# np.eye(n): n*n size의 단위행렬
print((np.eye(2))-C)

print(D-(np.eye(3)))

print(np.dot(3*np.eye(3),D))

